### PR TITLE
Create code_of_conduct.md

### PR DESCRIPTION
**Pull request by dduncanmccourt**
Please add this code of conduct to the papers repository

### CODE REVIEW

**Review by sbendar — COMMENTED** [review]
It looks good but the default convention on GitHub I think is to use all caps CODE_OF_CONDUCT.md

**Comment by dduncanmccourt** [comment]
Got it. Just renamed...do I need to resubmit?

**Review by sbendar — APPROVED** [review]
Looks good.

**Comment by dduncanmccourt** [comment]
Adding CODE_OF_CONDUCT.md

**Pull request merged**
